version: '3'
services:
  site:
    container_name: site
    image: alterway/php:5.4-apache
    environment:
      PHP_php5enmod: 'mysqli'
      HTTPD_a2enmod: 'rewrite headers'
    volumes:
      - "./public_html:/var/www/html"
    ports:
      - "3366:80"
    depends_on:
      - mysqldb
  phpmyadmin:
    container_name: dbadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "6666:80"
    environment:
      PMA_HOST: mysqldb
    depends_on:
      - mysqldb
  mysqldb:
    container_name: db
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQLDB}
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPWD}
      MYSQL_USER: ${MYSQLUSR}
      MYSQL_PASSWORD: ${MYSQLPWD}