  <ul>
    <li>{poweredby}</li>
    <li>- <a href="http://sourceforge.net/mail/?group_id=29581">MailingList</a></li>
    <li>- <a href="http://sourceforge.net/tracker/?group_id=29581&amp;atid=396656">BugReport</a></li>
    <li>- <a href="http://sourceforge.net/tracker/?group_id=29581&amp;atid=396657">SupportRequest</a></li>
    <li>- <a href="http://sourceforge.net/tracker/?group_id=29581&amp;atid=396659">FeatureRequests</a></li>
  </ul>

  {debug_info prepend='<div style="text-align: left;">' append='</div>'}
